name: Matrix test

on:
  workflow_call:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.jobName.outputs.output }}
    strategy:
      fail-fast: false
      matrix:
        option:
          [
            "1",
            "3"
          ]
    steps:
      - name: write
        run: |
          mkdir outputs
          echo ${{ matrix.option }} > outputs/output-${{ matrix.option }}.txt
      - uses: actions/upload-artifacts@v3
        with:
          name: outputs
          path: outputs/output-${{ matrix.option }}.txt

  test2:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifacts@v3
        with:
          name: outputs
      - run: ls -la outputs/
