name: Matrix test

on:
  workflow_call:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v2
      - name: Test docker
        run: |
          docker run --rm --platform linux/arm64 hello-world
